
spring:
  r2dbc:
    username: postgres
    password: 1832373
    url: r2dbc:postgresql://localhost:5432/order-manager
    pool:
      enabled: true
  thymeleaf:
    mode: HTML
logging:
  level:
    root: INFO
